### ISSUE TITLE
增加 swap 分区

### ISSUE THREAD

**Issue by RainbowXie** [umeiko/KlipperPhonesLinux#18]
手机做的 linux 系统始终有内存不足的问题，我搜到的方法都是通过另一个系统将其他分区减小，然后划分一个 swap 分区。但是手机设备好像不能这样。如何增加一个 swap 分区呢？

**Comment by umeiko** [comment]
有吗？除了1+8的红米2以外目前没有遇到内存不够用这种情况。我都是把系统刷在userdata里，你可以把system分区拿去用。

**Comment by RainbowXie** [comment]
我是拿来当服务器用的，所以不太够。主要是在这个设备不知道怎么操作，在系统里看不到 system 分区，可以在 recovery 里面用 parted 来重新分区吗？

**Comment by RainbowXie** [comment]
之前试过，发现刷完系统后 recovery 里连不上 adb 了。

**Comment by RainbowXie** [comment]
sb了，parted 可以直接拿来格式化了。
