### ISSUE TITLE
Redmi Note 4X (mido) Python3.8.10 安装shaketune报错

### ISSUE THREAD

**Issue by veyron9288** [umeiko/KlipperPhonesLinux#19]
<img width="559" alt="Snipaste_2024-06-14_09-07-21" src="https://github.com/umeiko/KlipperPhonesLinux/assets/9253620/5e86bda9-178a-40a2-aeeb-3fd2d3c9ff46">

**Comment by umeiko** [comment]
Ubuntu20.04自带的python版本3.8，shaketune需要3.9以上。可以尝试使用[Ubuntu24.04的包](https://github.com/umeiko/lk2nd/releases/tag/ubuntu24.04_xiaomi_msm8953)手动安装Klipper全家桶。

**Comment by veyron9288** [comment]
> Ubuntu20.04自带的python版本3.8，shaketune需要3.9以上。可以尝试使用[Ubuntu24.04的包](https://github.com/umeiko/lk2nd/releases/tag/ubuntu24.04_xiaomi_msm8953)手动安装Klipper全家桶。

ubuntu24刷上了，如何手动安装klipper，是要通过串口吗？

**Comment by veyron9288** [comment]
> Ubuntu20.04自带的python版本3.8，shaketune需要3.9以上。可以尝试使用[Ubuntu24.04的包](https://github.com/umeiko/lk2nd/releases/tag/ubuntu24.04_xiaomi_msm8953)手动安装Klipper全家桶。

ubuntu24刷上了，如何手动安装klipper，是要通过otg接键鼠上去，然后给手机连上wifi，最终ssh装对么

**Comment by umeiko** [comment]
> > Ubuntu20.04自带的python版本3.8，shaketune需要3.9以上。可以尝试使用[Ubuntu24.04的包](https://github.com/umeiko/lk2nd/releases/tag/ubuntu24.04_xiaomi_msm8953)手动安装Klipper全家桶。
> 
> ubuntu24刷上了，如何手动安装klipper，是要通过otg接键鼠上去，然后给手机连上wifi，最终ssh装对么

通过putty用串口连上去就行了
