### ISSUE TITLE
'timer too close erro

### ISSUE THREAD

**Issue by TT8174** [umeiko/KlipperPhonesLinux#2]
I use EBB36,but i got the timer too close erro.
but i don't know how to close cpu temprature.
help me
Thanks

**Comment by TT8174** [comment]
Error during homing, 'timer too close'
If you have a Qualcomm Snapdragon 625 model, disable CPU temperature monitoring in Klipper settings.

I can't find how to disable it.

**Comment by umeiko** [comment]
Found if “sensor_type: temperature_mcu” or  “sensor_type: temperature_host” in your configuration files, then removes them.

**Comment by umeiko** [comment]
> I use EBB36,but i got the timer too close erro. but i don't know how to close cpu temprature. help me Thanks

TTC happens when you are homing?

**Comment by Manasx100** [comment]
Same thing with a Snapdragon 435 (redmi 4x)
