### ISSUE TITLE
Redmi 4x KlipperScreen randomly restarting or black screen or registering inputs 3cm below

### ISSUE THREAD

**Issue by Manasx100** [umeiko/KlipperPhonesLinux#25]
When using KlipperScreen it restart says something about broken wayland pipe (I rotated the screen by 90 degrees but the other issues persist) ,sometimes after reboot there is just a black screen touching it doesn't fix it and a lot of times the touchscreen just doesn't work correctly it thinks I am touching it ~3cm below if horizontal or ~3cm to the left (possibly broken  screen or driver but in android no issues with the touchscreen)

**Comment by umeiko** [comment]
Redmi 4x have no GPU support and rendering by software. Rotating Screen may cause overload of its CPU. Maybe Just use the X11 with no Rotating is better.

**Comment by Manasx100** [comment]
> Redmi 4x have no GPU support and rendering by software. Rotating Screen may cause overload of its CPU. Maybe Just use the X11 with no Rotating is better.

Would an galaxy a7 2018 do better?

**Comment by Manasx100** [comment]
Something about Unknown-1 not having enough heads
