### ISSUE TITLE
红米Note4无限重启怎么解决，屏幕一直黑

### ISSUE THREAD

**Issue by hiliving** [umeiko/KlipperPhonesLinux#30]
按提示，解锁后，进入fastBoot，选择了数字4,的包，但是刷了一半无限重启，屏幕不亮，就振动一下，隔一会振动一下。也无法重新进入fastBoot

**Comment by umeiko** [comment]
尾插坏了而已

**Comment by hiliving** [comment]
> 尾插坏了而已

没有坏，是深度锁机了，我重新下载了官方包，又折腾了好久，解决了。是因为我误以为Note4是晓龙处理器，刷错了，其实是联发科的，重新刷了对应的包，好了。
