### ISSUE TITLE
Redmi 4X  WiFi

### ISSUE THREAD

**Issue by hwq826** [umeiko/KlipperPhonesLinux#6]
WiFi not working  

sit0: flags=193<UP,RUNNING,NOARP>  mtu 1480
        inet6 ::127.0.0.1  prefixlen 96  scopeid 0x90<compat,host>
        sit  txqueuelen 1000  (IPv6-in-IPv4)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

**Comment by umeiko** [comment]
Leave more details, or this issue will be closed soon.
