### ISSUE TITLE
USB/serial works only when supplying power to the printer motherboard

### ISSUE THREAD

**Issue by blvckmvgicdotexe** [umeiko/KlipperPhonesLinux#7]
Device: `xiaomi-mido`
I soldered cables for USB and jumped together ID and GND and usb devices do not get detected, my RAMPS board is detected only if I supply 5v from my PSU (5v standby) so perhaps some sort of power issue?

**Comment by blvckmvgicdotexe** [comment]
Apparently, according to schematics, the rightmost pin close to USB_ID is not GND but BAT_THERM, so in theory USB_ID should be connected to the rightmost pin in the picture and the whole system could be powered by connecting 5v to VBUS while allowing to keep the battery for backup (my PSU has 5v standby)

![Screenshot_20240414_190715](https://github.com/umeiko/KlipperPhonesLinux/assets/36662385/9fce1a0f-a47e-403d-8a2b-96e8ae27d78c)

**Comment by umeiko** [comment]
yep, Seems TP2412 is not usb_gnd, I missed it because it's very close to usb pins. I grounded TP2404, TP2412 and TP2411 together, then mido boot up normally and USB-serial working good.
