### ISSUE TITLE
麦芒5 4+64g，刷新klipper固件后，wifi链接不稳定，otg不能用

### ISSUE THREAD

**Issue by zetenbuzi** [umeiko/KlipperPhonesLinux#8]
按教程刷新了3次，没有改善，可能是硬件上的差异。刷回官方固件wifi正常，刷机前是官方固件未作任何修改，反映下这个bug，希望改进谢谢！

**Comment by umeiko** [comment]
bootloader问题解锁不当导致基带固件问题，不在linux内核讨论层面。此issue将关闭。
