### ISSUE TITLE
mi 5s 用新内核直接进入9008

### ISSUE THREAD

**Issue by kschen202115** [umeiko/KlipperPhonesLinux#9]
用这个https://gitlab.com/msm8996-mainline/linux/按照教程编译刷入后，无法正常启动，会进入9008模式，想换内核的原因是用这个内核的pmos可以正常使用wifi而且也加入了米5s的设备树

**Comment by umeiko** [comment]
mi5s本来就有刷机包而且可以正常用wifi。自己编译固件但是你没办法提供任何可供参考的信息没有办法帮到你。建议直接用我已经移植好的5s刷机包。
